name: PLAZMER-ENGINE
version: ${version}
main: t.me.p1azmer.engine.NexEngine
author: "plazmer"
website: "t.me/p1azmer"
api-version: 1.17
softdepend: [ Vault ]
load: STARTUP
libraries:
  - com.zaxxer:HikariCP:5.0.1
  - it.unimi.dsi:fastutil:8.5.11